// English version of the main demo case (synthetic, de-identified).
// Same structure and codes as MOCK_REPORT in App.jsx; only free text is translated,
// so every client-side screen and score runs identically in both languages.
export const MOCK_REPORT_EN = {
  thong_tin_benh_nhan: { ho_ten:"PATIENT A (DEMO)", ngay_sinh:"09/11/1963", tuoi:62, gioi_tinh:"Male", dia_chi:"Hanoi, Vietnam", ngay_vao_vien:"24/09/2025", ngay_ra_vien:"03/10/2025", so_benh_an:"25.019647" },
  chan_doan_chinh: "Status post mechanical aortic valve replacement (On-X 23). Mixed aortic stenosis and regurgitation. Dilated ascending aorta. Mild myocardial bridging of the LAD. Angina. Heart failure.",
  ly_do_vao_vien: "Fatigue and dyspnea; echocardiography showed severe aortic stenosis; admitted for valve replacement.",
  tien_su_benh: "Known aortic stenosis and regurgitation. Office worker. No history of diabetes.",
  phau_thuat: { ngay:"26/09/2025", phuong_phap:"Mechanical aortic valve replacement (On-X 23)", ket_qua:"Successful. Prosthetic valve well seated and functioning normally on post-op echo.", bac_si_phau_thuat:"Dr. X / Dr. Y" },
  dien_bien_lam_sang: [
    { ngay:"24/09/2025", mo_ta:"Admitted to Adult Cardiac Surgery. Diagnosed with aortic stenosis and regurgitation; surgery scheduled.", loai:"binh_thuong" },
    { ngay:"26/09/2025", mo_ta:"Surgery at 12:42. Successful mechanical aortic valve replacement (On-X 23).", loai:"binh_thuong" },
    { ngay:"26/09/2025", mo_ta:"Post-op: CRP 241.42 mg/L, markedly raised white cells. Started Buflan 2g (cefoperazone + sulbactam).", loai:"canh_bao" },
    { ngay:"27/09/2025", mo_ta:"CRP down to 130.17 mg/L. Continued Buflan 2g, IV furosemide, Vincerol anticoagulation.", loai:"bat_thuong" },
    { ngay:"30/09/2025", mo_ta:"CRP 106.61 mg/L. Echo: EF 50%, aortic gradient 16 mmHg, pleural effusion. Prosthetic valve functioning.", loai:"bat_thuong" },
    { ngay:"03/10/2025", mo_ta:"Discharged. CRP down to 42.3 mg/L. INR 2.25 (in range). NT-proBNP 2280 pg/mL. Follow-up on 10/10.", loai:"binh_thuong" },
  ],
  vital_signs: [
    { ngay:"28/09", crp:130.2, wbc:16.6 },
    { ngay:"29/09", crp:241.4, wbc:15.3 },
    { ngay:"01/10", crp:106.6, wbc:14.5 },
    { ngay:"03/10", crp:42.3,  wbc:11.8 },
  ],
  xet_nghiem_truoc_mo: { ghi_chu:"Pre-op tests: EF 61 to 74%, peak aortic gradient 71 mmHg (echo 12/09, severe stenosis). Not yet on anticoagulation." },
  xet_nghiem_meta: [
    { key:"HGB",       val:"116 g/L",     rawVal:116,   unit:"g/L",    desc:"Hemoglobin",              normal:"130-172", status:"low",    trend:[122,127,115,116], trendDates:["26/09","27/09","01/10","03/10"], arrow:"down" },
    { key:"WBC",       val:"11.79 G/L",   rawVal:11.79, unit:"G/L",    desc:"White blood cells",       normal:"4-10",    status:"high",   trend:[17.2,14.5,11.79], trendDates:["27/09","01/10","03/10"], arrow:"down" },
    { key:"PLT",       val:"308 G/L",     rawVal:308,   unit:"G/L",    desc:"Platelets",               normal:"150-400", status:"normal", trend:[151,217,308], trendDates:["26/09","29/09","03/10"], arrow:"up" },
    { key:"Creatinin", val:"77 µmol/L",   rawVal:77,    unit:"µmol/L", desc:"Renal function",          normal:"62-106",  status:"normal", trend:[74,77,77], trendDates:["27/09","29/09","03/10"], arrow:"ok" },
    { key:"Na+",       val:"131 mmol/L",  rawVal:131,   unit:"mmol/L", desc:"Serum sodium",            normal:"135-145", status:"low",    trend:[133,127,131], trendDates:["29/09","30/09","03/10"], arrow:"up" },
    { key:"K+",        val:"3.82 mmol/L", rawVal:3.82,  unit:"mmol/L", desc:"Serum potassium",         normal:"3.5-5.1", status:"normal", trend:[3.34,5.1,3.82], trendDates:["29/09","30/09","03/10"], arrow:"down" },
    { key:"Albumin",   val:"31.8 g/L",    rawVal:31.8,  unit:"g/L",    desc:"Serum albumin",           normal:"35-52",   status:"low",    trend:[31.8], trendDates:["29/09"], arrow:"down" },
    { key:"CRP",       val:"42.3 mg/L",   rawVal:42.3,  unit:"mg/L",   desc:"Inflammation (latest)",   normal:"<5",      status:"high",   trend:[241.4,106.6,42.3], trendDates:["29/09","01/10","03/10"], arrow:"down" },
    { key:"INR",       val:"2.25",        rawVal:2.25,  unit:"",       desc:"Coagulation (at discharge)", normal:"2.0-3.0", status:"normal", trend:[1.24,5.97,2.25], trendDates:["26/09","27/09","03/10"], arrow:"down" },
    { key:"NT-proBNP", val:"2280 pg/mL",  rawVal:2280,  unit:"pg/mL",  desc:"Heart failure marker",    normal:"<125",    status:"high",   trend:[317,2280], trendDates:["24/09","29/09"], ngay:"29/09/2025", arrow:"up" },
    { key:"EF",        val:"71%",         rawVal:71,    unit:"%",      desc:"Ejection fraction (latest echo 26/05/2026)", normal:"55-70", status:"high", trend:[50,44,58,71], trendDates:["30/09","10/10","28/10","26/05"], arrow:"up" },
  ],
  sieu_am_tim: {
    lan_kham: [
      { ngay:"31/07/2025", nguon:"PACS", chan_doan:"AS + AR, mild MR", ef:61, grad_max:54, grad_tb:34, hoc:"Mild-moderate", phase:"truoc_mo", ghi_chu:"Pre-op. Moderate aortic stenosis, valve area 1.23 cm². Dilated left atrium, LAVI 52.", canh_bao:false },
      { ngay:"12/09/2025", nguon:"PACS", chan_doan:"AS + AR", ef:74, grad_max:71, grad_tb:51, hoc:"Mild-moderate", phase:"truoc_mo", ghi_chu:"Pre-op. SEVERE aortic stenosis, valve area 1.06 cm². Extensive valve damage.", canh_bao:false },
      { ngay:"30/09/2025", nguon:"HIS Doppler", chan_doan:"Mechanical aortic valve", ef:50, grad_max:16, grad_tb:null, hoc:"Mild (transvalvular)", phase:"sau_mo", ghi_chu:"Post-op day 4. EF down to 50%. Bilateral pleural effusion, small pericardial effusion.", canh_bao:true },
      { ngay:"10/10/2025", nguon:"PACS", chan_doan:"Mechanical aortic valve", ef:44, grad_max:20, grad_tb:16, hoc:"Mild (transvalvular)", phase:"sau_mo", ghi_chu:"1-week follow-up. EF severely reduced to 44%. LARGE pericardial effusion with mild right-ventricular compression.", canh_bao:true },
      { ngay:"28/10/2025", nguon:"PACS", chan_doan:"Mechanical aortic valve", ef:58, grad_max:14, grad_tb:5, hoc:"Mild (transvalvular)", phase:"hoi_phuc", ghi_chu:"EF recovered to 58%. Pleural and pericardial effusions resolved.", canh_bao:false },
      { ngay:"25/11/2025", nguon:"PACS", chan_doan:"Mechanical aortic valve", ef:71, grad_max:15, grad_tb:9, hoc:"Mild (transvalvular)", phase:"hoi_phuc", ghi_chu:"EF well recovered to 71%. No pleural or pericardial effusion.", canh_bao:false },
      { ngay:"21/01/2026", nguon:"PACS", chan_doan:"Mechanical aortic valve, mild MS/MR", ef:58, grad_max:13, grad_tb:8, hoc:"Mild (transvalvular)", phase:"tai_kham", ghi_chu:"Mild mitral stenosis (area 2.0 cm²), mild MR. Dilated left atrium.", canh_bao:false },
      { ngay:"10/04/2026", nguon:"PACS", chan_doan:"Mechanical aortic valve", ef:69, grad_max:11, grad_tb:null, hoc:"Mild (transvalvular)", phase:"tai_kham", ghi_chu:"Concentric LV hypertrophy. Dilated left atrium, LAVI 55 ml/m².", canh_bao:false },
      { ngay:"26/05/2026", nguon:"PACS", chan_doan:"Mechanical aortic valve", ef:71, grad_max:8, grad_tb:null, hoc:"Mild (transvalvular)", phase:"tai_kham", ghi_chu:"Prosthetic valve functioning normally. Dilated left atrium, LAVI 50 ml/m².", canh_bao:false, latest:true },
    ],
  },
  canh_bao_nguy_co: [
    { mo_ta:"10/10/2025: large pericardial effusion with mild right-ventricular compression and EF down to 44%. Post-op effusion complication requiring close follow-up; resolved at later visits.", muc_do:"cao", can_cu:"Echo 10/10/2025: large pericardial effusion, mild RV compression, EF 44%." },
    { mo_ta:"NT-proBNP 2280 pg/mL: very high; heart-failure marker requiring close follow-up after discharge.", muc_do:"cao", can_cu:"Lab 29/09/2025: NT-proBNP 2280 pg/mL (normal below 125 pg/mL)." },
    { mo_ta:"Wide INR swings around the anticoagulant switch: from 1.24 (below range, valve thrombosis risk) up to 5.97 (above range, bleeding risk) before settling at 2.25. The On-X mechanical valve needs INR 2.0 to 3.0; monitor closely.", muc_do:"cao", can_cu:"INR monitoring 26/09 to 10/10/2025. Switched from warfarin (inpatient) to Vincerol at discharge." },
    { mo_ta:"CRP still 42.3 mg/L at discharge (normal below 5). Post-op inflammation not yet back to normal.", muc_do:"trung_binh", can_cu:"Lab 03/10/2025: CRP 42.3 mg/L, peak 241.42 on 29/09." },
    { mo_ta:"Persistent post-op hyponatremia: Na+ 127 to 133 mmol/L (normal 135 to 145), lowest 127 on 30/09. Monitor electrolytes on diuretics.", muc_do:"trung_binh", can_cu:"Electrolytes 24/09 to 03/10/2025: lowest Na+ 127 mmol/L (30/09)." },
    { mo_ta:"Low albumin 31.8 g/L (normal 35 to 52) and mild anemia (HGB 116 g/L). Affects drug distribution and wound healing; nutrition support needed.", muc_do:"thap", can_cu:"Lab 29/09/2025: albumin 31.8 g/L. CBC 03/10: HGB 116 g/L." },
  ],
  ket_luan_giai_doan: {
    1: "Admitted with severe aortic stenosis (valve area 1.06 cm², gradient 71/51 mmHg). Valve replacement was appropriately indicated. Good pre-op cardiac function (EF 74%), normal renal function, INR 1.24 (not yet anticoagulated).",
    2: "Successful surgery. Complicated post-op course: strong inflammatory response (CRP peak 241 mg/L), wide INR swings (1.24 to 5.97, then 2.25), persistent low Na+, low albumin, transient EF drop (50%) at discharge. Discharged 03/10 with INR in range and CRP falling.",
    3: "Post-op pericardial effusion (10/10) resolved completely. EF recovered well to 71%. On-X valve functioning normally (gradient 8 mmHg). Left atrium still dilated (LAVI 50 ml/m²); monitor for atrial fibrillation. No repeat NT-proBNP since discharge to assess outpatient heart failure.",
  },
  clinical_takeaway: [
    { txt:"The patient is past the high-risk post-op period and is now stable as an outpatient.", loai:"good" },
    { txt:"Cardiac function has almost fully recovered (EF 71%); the On-X valve works well; pericardial effusion resolved.", loai:"good" },
    { txt:"Still to monitor: mechanical-valve anticoagulation (INR target 2.0 to 3.0), electrolytes, and AF risk from the dilated left atrium.", loai:"watch" },
    { txt:"No repeat NT-proBNP since discharge to assess true outpatient heart failure.", loai:"watch" },
  ],
  ly_luan_lam_sang: [
    { muc:"critical", phase:2, tieu_de:"Complex picture: low Na+ after major cardiac surgery with low albumin",
      noi_dung:"On 29/09: (1) Na+ 131 mmol/L (mildly low) plus (2) albumin 31.8 g/L (low) plus (3) CRP still 130 mg/L. Low albumin reduces oncotic pressure and promotes fluid leak, explaining the pleural and pericardial effusions. It also alters Vincerol distribution, making INR less predictable. Nutrition support is needed alongside diuretics." },
    { muc:"critical", phase:2, tieu_de:"Dangerous INR swings: 1.24, then 5.97, then 2.25",
      noi_dung:"INR 1.24 (24/09): mechanical valve thrombosis risk. INR 5.97 (27/09, peak): serious bleeding risk. Cause: switching anticoagulant regimens plus Buflan (cefoperazone has vitamin K antagonist-like activity) potentiating Vincerol. Discharge INR 2.25 is within the 2.0 to 3.0 target for the On-X valve." },
    { muc:"critical", phase:3, tieu_de:"EF 44% with a large pericardial effusion: serious post-op complication",
      noi_dung:"EF fell from 50% (30/09) to 44% (10/10) with a large pericardial effusion and mild RV compression: a post-op pericardial effusion (seen in roughly 1 to 3% of cases), not chronic heart failure. Differentiate from Dressler syndrome. Outcome: resolved by the 28/10 visit (EF 58%, no effusion)." },
    { muc:"info", phase:3, tieu_de:"NT-proBNP 2280 pg/mL (29/09, Phase 2): do not diagnose heart failure from this value",
      noi_dung:"NT-proBNP was measured on 29/09, three days after major cardiac surgery. Elevated NT-proBNP right after cardiac surgery is common and may not reflect chronic heart failure. The patient is now in Phase 3 with EF recovered to 71% (26/05/2026). Recommendation: repeat NT-proBNP at the next visit for a true outpatient baseline." },
    { muc:"warning", phase:3, tieu_de:"Persistently dilated left atrium (LAVI 50 to 55 ml/m²): monitor for AF",
      noi_dung:"The left atrium was dilated before surgery (LAVI 52) and remains dilated in Phase 3 (LAVI 50 to 55). Persistent LA dilation is a risk factor for atrial fibrillation. With a mechanical valve on anticoagulation, new AF would raise the INR target to 2.5 to 3.5. Recommendation: periodic ECG, Holter if palpitations." },
  ],
  problem_status: {
    hien_tai: [
      { ten:"On-X mechanical valve", trang_thai:"active", mo_ta:"Functioning well, gradient 8 mmHg" },
      { ten:"Anticoagulation (Vincerol)", trang_thai:"active", mo_ta:"Lifelong, INR target 2.0 to 3.0" },
      { ten:"Dilated left atrium (LAVI 50 to 55 ml/m²)", trang_thai:"monitoring", mo_ta:"Persistent; AF risk; needs ECG/Holter" },
      { ten:"Mild mitral stenosis", trang_thai:"monitoring", mo_ta:"Found 21/01/2026; monitor progression" },
    ],
    da_qua: [
      { ten:"Pericardial effusion with mild RV compression", mo_ta:"10/10/2025; resolved by the 28/10 visit" },
      { ten:"EF down to 44%", mo_ta:"10/10/2025 due to effusion; recovered to 71%" },
      { ten:"INR up to 5.97", mo_ta:"27/09/2025; stabilized at 2.25" },
      { ten:"Post-op hyponatremia", mo_ta:"Lowest Na+ 127 (30/09), inpatient phase" },
      { ten:"Low albumin", mo_ta:"31.8 g/L (29/09), inpatient phase" },
    ],
  },
  hanh_dong_uu_tien: [
    { uu_tien:1, viec:"Check INR regularly", ly_do:"The On-X mechanical valve needs lifelong anticoagulation with INR kept at 2.0 to 3.0. This is the ongoing reason, independent of the short antibiotic course that has ended." },
    { uu_tien:2, viec:"Repeat electrolytes (Na+, K+) and creatinine", ly_do:"Ongoing combination of the diuretic Agifuros with the SGLT2 inhibitor Forxiga; risk of hyponatremia and electrolyte disturbance." },
    { uu_tien:3, viec:"ECG, consider 24-hour Holter to screen for AF", ly_do:"A persistently dilated left atrium (LAVI 50 to 55 ml/m²) is an AF risk factor in a mechanical-valve patient." },
    { uu_tien:4, viec:"Repeat NT-proBNP for an outpatient baseline", ly_do:"NT-proBNP 2280 pg/mL was measured on post-op day 3 and does not reflect current outpatient heart failure status." },
  ],
  thuoc_cuoi_ky: [
    { ten_thuoc:"Buflan 2g (Cefoperazone + Sulbactam)", nhom:"Antibiotic",    lieu:"2 vials/day",   cach_dung:"IV infusion at 9:00 and 21:00", bat_dau:"28/09", ket_thuc:"03/10", color:"#EF4444" },
    { ten_thuoc:"Medoxasol 500mg (Levofloxacin)",       nhom:"Antibiotic",    lieu:"2 tablets/day", cach_dung:"Oral at 9:00 and 20:00", bat_dau:"03/10", so_luong:14, vien_moi_ngay:2, color:"#F97316" },
    { ten_thuoc:"Vincerol 1mg (Acenocoumarol)",         nhom:"Anticoagulant", lieu:"1 tablet/day",  cach_dung:"Oral at 20:00 daily", bat_dau:"03/10", keo_dai:true, color:"#8B5CF6" },
    { ten_thuoc:"Agifuros 40mg (Furosemide)",            nhom:"Diuretic",      lieu:"1 tablet/day",  cach_dung:"Oral at 9:00", bat_dau:"28/09", keo_dai:true, color:"#06B6D4" },
    { ten_thuoc:"Forxiga 10mg (Dapagliflozin)",         nhom:"Cardiovascular",lieu:"1 tablet/day",  cach_dung:"Oral in the morning", bat_dau:"26/09", keo_dai:true, color:"#10B981" },
    { ten_thuoc:"Pantoloc 40mg (Pantoprazole)",         nhom:"Gastric",       lieu:"1 tablet/day",  cach_dung:"Oral at 6:00 before meals", bat_dau:"24/09", keo_dai:true, color:"#3B82F6" },
  ],
  tom_tat_toan_canh: "PRE-OP PHASE: 62-year-old man with known aortic stenosis and regurgitation, admitted on 24/09/2025 for chest pain and dyspnea. Pre-op echo showed severe aortic stenosis with a peak gradient of 71 mmHg and preserved EF. POST-OP INPATIENT PHASE: On 26/09/2025 he underwent mechanical aortic valve replacement (On-X 23) with a successful result; the valve works well and the gradient fell to 8 to 16 mmHg. Early post-op there was a strong inflammatory response (CRP peak 241 mg/L on 29/09, then falling) and NT-proBNP of 2280 pg/mL, consistent with the immediate post-cardiac-surgery period. He was discharged stable on 03/10/2025 on Vincerol anticoagulation, a diuretic and antibiotics. OUTPATIENT FOLLOW-UP PHASE: At the 10/10/2025 visit (about one week after discharge) EF had fallen to 44% with a pericardial effusion mildly compressing the right ventricle; this was the issue needing the closest follow-up. Later visits showed clear improvement: the effusion resolved and EF recovered to 58% (28/10) and then 71% (latest, 26/05/2026). INR fluctuated and is now within the 2.0 to 3.0 mechanical-valve target.",
  dau_hieu_sinh_ton: { ngay:"03/10/2025", ha_tt:120, ha_ttr:70, mach:78, nhiet_do:36.8, nhip_tho:18, spo2:97, lactate:1.4 },
}
