FROM node:20-slim AS build

WORKDIR /app

RUN npm install esbuild@0.27.7 react@19.2.6 react-dom@19.2.6 @supabase/supabase-js

COPY . .

# Copy mount.jsx ra cùng cấp với App.jsx
COPY docker_setup/mount.jsx ./mount.jsx

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY

RUN test -n "$VITE_SUPABASE_URL" || (echo "Missing VITE_SUPABASE_URL" && exit 1)
RUN test -n "$VITE_SUPABASE_ANON_KEY" || (echo "Missing VITE_SUPABASE_ANON_KEY" && exit 1)

RUN npx esbuild ./mount.jsx \
    --bundle \
    --loader:.jsx=jsx \
    --jsx=automatic \
    --format=esm \
    --define:import.meta.env.VITE_SUPABASE_URL=\"${VITE_SUPABASE_URL}\" \
    --define:import.meta.env.VITE_SUPABASE_ANON_KEY=\"${VITE_SUPABASE_ANON_KEY}\" \
    --outfile=/app/mount.js \
    --minify


FROM nginx:alpine

COPY --from=build /app/mount.js /usr/share/nginx/html/mount.js
COPY docker_setup/index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]